// Prompts for ElevenLabs Music and Sound Effects. `seconds` is the length to ask for.
export const MUSIC = [
  { id: 'music_boss_neco', seconds: 60, loop: true, note: 'replaces the current Neco theme',
    prompt: 'An eerie arcade chase in a mirror dimension: pulsing analogue synth bass, reversed reverb swells, insect-skitter percussion, a warped melody that repeats and detunes, tension building, 130 bpm, seamless loop, no vocals.' },
  { id: 'music_boss_umma', seconds: 60, loop: true, note: 'replaces the current UMMA theme',
    prompt: 'A clanky, cheerful arcade construction-site march with kitchen percussion: pots and pans, a cleaver on a wooden block, a rice-cooker steam whistle, a bouncy chiptune bass, 120 bpm, playful but relentless, seamless loop, no vocals.' },
  { id: 'music_hidden', seconds: 90, loop: true, note: 'the hidden level',
    prompt: 'A bright, bouncy platformer theme in fat 8-bit chiptune with a slightly unhinged orchestral sparkle: jumpy bass, a cheeky lead melody, marimba fills, 140 bpm, sunny and mischievous, seamless loop, no vocals.' },
  { id: 'music_star', seconds: 30, loop: true, note: 'plays while invincible from the nuke',
    prompt: 'A frantic invincibility theme in an urgent 8-bit style: racing arpeggios, siren-like leads, hammering kick, 170 bpm, thirty seconds, seamless loop, no vocals.' },
  { id: 'sting_pastor', seconds: 4, loop: false, note: 'when Pastor Dale appears',
    prompt: 'A four second church-organ sting: a big pompous major chord with a cheesy tremolo and a tiny cash-register ding at the end.' },
  { id: 'sting_podcaster', seconds: 4, loop: false, note: 'when Buck Mallory appears',
    prompt: 'A four second radio sting: a burst of static, a stretched airhorn, a paranoid low synth drone, and a sharp click.' },
  { id: 'sting_bossboss', seconds: 3, loop: false, note: "when the Boss's Boss appears",
    prompt: 'A three second corporate notification sting: a bright inoffensive marimba chime followed by a slightly sinister second chime.' },
];

export const SFX = [
  { id: 'sfx_plane_flyby', seconds: 3, group: 'Stage 2 hazard', prompt: 'A small propeller plane flying past low overhead, a Doppler whoosh from left to right.' },
  { id: 'sfx_package_whistle', seconds: 2, group: 'Stage 2 hazard', prompt: 'A falling bomb whistle, the pitch dropping from high to low.' },
  { id: 'sfx_powder_burst', seconds: 2, group: 'Stage 2 hazard', prompt: 'A big soft burst of white powder: a deep thump followed by a long airy hiss and a cough.' },
  { id: 'sfx_beam_hum', seconds: 2, group: 'Stage 4 hazard', prompt: 'A sci-fi tractor beam: a rising warbling hum with a gentle lifting whoosh.' },
  { id: 'sfx_stamp', seconds: 1, group: 'Stage K1 hazard', prompt: 'A heavy rubber stamp slamming onto paper, a single dull thud and a paper slap.' },
  { id: 'sfx_mirror_flip', seconds: 1, group: 'Stage K2 hazard', prompt: 'A mirror flipping: a glassy swish with a soft reversed chime.' },
  { id: 'sfx_narrator_lie', seconds: 1, group: 'Stage K3 hazard', prompt: 'A cheerful, too-bright confirmation ding with a faint sinister undertone.' },
  { id: 'sfx_blackout', seconds: 1, group: 'Stage K4 hazard', prompt: 'A power cut: a descending electrical whine into a heavy click and silence.' },
  { id: 'sfx_croc_bounce', seconds: 1, group: 'UMMA girder climb', prompt: 'A plastic clog shoe bouncing on a metal girder: a hollow clonk with a rubbery squeak.' },
  { id: 'sfx_croc_throw', seconds: 1, group: 'UMMA girder climb', prompt: 'A quick underarm throw: a soft whoosh and a small grunt of effort.' },
  { id: 'sfx_jar_smash', seconds: 1, group: 'UMMA girder climb', prompt: 'A ceramic jar smashing with a hiss of hot steam and a bubbling splash.' },
  { id: 'sfx_cent_skitter', seconds: 1, group: 'Neco centipede', prompt: 'A many-legged insect skittering rapidly over glass, tiny fast ticks.' },
  { id: 'sfx_cent_overload', seconds: 2, group: 'Neco centipede', prompt: 'A creature swelling and popping: a rising squeal, a glassy crack, a wet burst and sparkling fragments.' },
  { id: 'sfx_hl_jump', seconds: 1, group: 'Hidden level', prompt: 'A cartoon frog hop: a springy boing with a wet slap.' },
  { id: 'sfx_hl_stomp', seconds: 1, group: 'Hidden level', prompt: 'A squishy stomp on a small enemy: a wet crunch and a rubbery squeak.' },
  { id: 'sfx_hl_powerup', seconds: 1, group: 'Hidden level', prompt: 'A rising cartoon power-up: a bubbling whoosh and a fat happy chime.' },
  { id: 'sfx_hl_fire', seconds: 1, group: 'Hidden level', prompt: 'A short fire breath: a whoosh of flame with a crackle.' },
  { id: 'sfx_hl_nuke', seconds: 2, group: 'Hidden level', prompt: 'A radioactive pickup: a dramatic rising siren swell and a glassy shimmer.' },
  { id: 'sfx_hl_shrink', seconds: 1, group: 'Hidden level', prompt: 'A sad deflating shrink: a downward squeal and a soft pop.' },
  { id: 'sfx_hl_win', seconds: 3, group: 'Hidden level', prompt: 'A triumphant cartoon victory fanfare with a big detonator plunger click and an explosion.' },
  { id: 'sfx_skip_scream', seconds: 1, group: 'Influencer', prompt: 'A comedic short scream of panic, cut off, then a strangled sob, cartoonish and dry.' },
  { id: 'sfx_card_pop', seconds: 1, group: 'Interrupters', prompt: 'A cheap notification pop: a bubbly blip with a tiny sparkle.' },
];
