// The live comment section. Pure data: who is in the chat, what they say, and
// what they say back to the game. The panel that shows it is ui/livechat.js.
// Everyone here is invented. The scams are the joke, not a real offer.

// Regular chatters, grouped by what kind of person they are. Each kind has its
// own pool of handles and lines; the feed mixes them by weight.
export const KINDS = {
  fan: {
    weight: 9,
    handles: ['froglover_4ever', 'ribbit_or_riot', 'pondmom_87', 'LilyPadLucy', 'sir_hops_a_lot', 'tadpole_dad', 'Frog_Stan_2026', 'wet_and_wholesome'],
    lines: [
      'I would die for this frog. I would die for this frog TWICE.',
      'he is so tiny and so brave and I am not okay',
      'protect the frog at all costs 🐸',
      'that is MY son and he is doing his best',
      'the way he eats bombs with zero fear... king behaviour',
      'frog for president. I said what I said.',
      'every time he dies a little bit of me dies too and then I clap',
      'he has done nothing wrong ever in his life',
      'not the tiny little gulp he does 😭😭😭',
      'I have watched this frog for four hours and I have never been happier',
      'sending love to the frog and his weird little feet',
      'someone give this frog a hug and a lawyer',
      'best. frog. ever. no I will not be taking questions',
      'he really said "I will eat that explosive" and then DID',
      'this frog has more character arc than my entire family',
    ],
  },
  kermit: {
    weight: 5,
    handles: ['KermitDidItFirst', 'muppet_maniac', 'its_not_easy_being_green', 'Kermit_or_nothing', 'StatlerAndWaldorf_fan', 'MissPiggyStan'],
    lines: [
      'this is not Kermit and I am OFFENDED',
      'Kermit would never eat a bomb. Kermit has BOUNDARIES.',
      'it is not easy being green but it IS easy being better than this frog',
      'KERMIT. KERMIT. KERMIT. KERMIT.',
      'where is the banjo. where is the rainbow connection. this is a hate crime against felt',
      'my Kermit tattoo just started crying',
      'meanwhile Kermit is out here doing HONEST work with a pig',
      'imagine being a frog and NOT being in the Muppets',
      'Kermit has never once been on fire. respect the man.',
      'this frog has not paid his dues to Jim Henson and it SHOWS',
      'I want to talk to the frog manager',
    ],
  },
  reaper: {
    weight: 7,
    handles: ['let_him_die', 'frog_must_perish', 'squash_the_frog', 'car_go_brrr', 'DeathToFrog', 'bet_he_dies_in_10', 'hamburger_hitman'],
    lines: [
      'kill him',
      'I am only here for the frog to die',
      'somebody get a taxi to hit him please I am begging',
      'bet 500 he dies in ten seconds. no takers? cowards.',
      'die die die die die die die',
      'that frog has been alive far too long',
      'make him explode. make him explode. MAKE HIM EXPLODE',
      'the algorithm demands sacrifice',
      'a hamburger is coming for you frog. you are not ready.',
      'I refuse to leave until this frog is flat',
      'is it too late to rig it so he dies',
      'no more bombs. just cars. lots of cars. all the cars.',
      'this frog owes me money and I want him dead',
    ],
  },
  sweary: {
    weight: 8,
    handles: ['fuck_this_frog', 'ass_goblin_9000', 'shitposter_supreme', 'HolyFuckingHell', 'dumbass_dan', 'no_filter_nancy', 'PissedOffPete'],
    lines: [
      'what the actual FUCK was that',
      'holy shit he made it. holy SHIT.',
      'this game is dogshit and I cannot stop watching',
      'fucking hell frog just use the goddamn bridge',
      'I would kill a man for this frog. a small man. a smaller man than me.',
      'that was the stupidest shit I have ever seen and I love it',
      'bro moves like a drunk raccoon on a trampoline',
      'oh you absolute son of a bitch, you did it',
      'why the fuck is there a hamburger driving a car',
      'my ass is genuinely clenched right now',
      'this is the shittiest thing I have ever loved',
      'fuck it I am bringing a snack. do not start without me.',
      'no this is bullshit the road is rigged',
      'I am so fucking invested and I hate that I am invested',
    ],
  },
  skeptic: {
    weight: 8,
    handles: ['originality_police', 'actually_frogger_did_it', 'ripoff_detector', 'dev_stole_my_idea', 'itch_io_veteran', 'nintendo_lawyer_1', 'bootleg_bill'],
    lines: [
      'this is just Frogger with extra steps',
      'Frogger did it first. Punch-Out did it first. what did YOU do first?',
      'imagine ripping off Frogger AND Punch-Out AND Space Invaders in one game',
      'the plagiarism is CRAZY right now',
      'my lawyer has been notified. my lawyer is also my cousin.',
      'I saw this exact game on a cereal box in 1994',
      'the devs just play old games and then say "mine now"',
      'not even the frog is original. Kermit did it first. and better.',
      'this is a ripoff and I am telling EVERYONE',
      'somebody call Nintendo. somebody call Konami. somebody call my mom.',
      '"inspired by". sure. sure sure sure.',
      'I could make this in a weekend with a stick and a dream',
      'I have seen better frogs in a puddle behind a Wendy\'s',
    ],
  },
  troll: {
    weight: 9,
    handles: ['xX_Dr_Chaos_Xx', 'lolmao_2000', 'first_time_caller', 'cringe_lord_1', 'imagine_being_you', 'ratio_king', 'notyourfriend_dave', 'gigachad_moth'],
    lines: [
      'first',
      'ratio',
      'L + frog + who asked',
      'you guys still play this? in 2026?',
      'my grandmother plays better than this and she has been dead since 2019',
      'skill issue',
      'this chat is cooked',
      'streamer is cooked. game is cooked. frog is cooked.',
      'lmao the frog is bad',
      'ok but why is the frog wearing gloves. he has no fingers.',
      'nobody: … the frog: 🐸',
      'who let the dogs out. who. who. who who who.',
      'I came here for a fight and stayed for the frog. this is not what I wanted.',
      'you just lost the game',
      'unsubscribed. resubscribed. unsubscribed. resubscribed.',
    ],
  },
  caps: {
    weight: 4,
    handles: ['CAPS_LOCK_CARL', 'LOUD_LARRY', 'WHY_ARE_WE_YELLING', 'STOPTALKINGTOME'],
    lines: [
      'WHY IS EVERYONE SO CALM ABOUT THIS',
      'THE FROG IS ALIVE. THE FROG IS ALIVE. I REPEAT THE FROG IS ALIVE.',
      'I HAVE BEEN AWAKE FOR THREE DAYS AND THIS IS THE BEST THING I HAVE EVER SEEN',
      'WHAT IS HAPPENING. WHY IS THE ROAD LIKE THAT.',
      'DO NOT TALK TO ME UNTIL THE FROG IS SAFE',
      'I CAN FEEL MY PULSE IN MY TEETH',
    ],
  },
  weird: {
    weight: 8,
    handles: ['bob_from_accounting', 'is_the_frog_single', 'conspiracy_carol', 'sleepy_gary_zzz', 'my_cat_watches_this', 'moth_to_the_flame', 'oat_milk_enjoyer', 'toaster_bath_tim'],
    lines: [
      'is the frog single',
      'the frog is the government and you all know it',
      'my cat is watching this and hasn\'t blinked in eleven minutes',
      'has anyone tried turning the frog off and on again',
      'I am eating a whole rotisserie chicken in the bath and it is going great',
      'anyone else here past their bedtime? just me? cool. cool cool.',
      'this reminds me of my third divorce',
      'the frog looks exactly like my landlord',
      'I put my phone in rice and it still works. unrelated. hi.',
      'if the frog wins I am quitting my job',
      'my mom asked what I was watching and I said "a frog" and she looked at me differently',
      'blink twice if the frog is in danger',
      'somebody please tell my wife I am not coming to bed',
      'the Wi-Fi is haunted but the frog is fine',
    ],
  },
  newbie: {
    weight: 6,
    handles: ['just_got_here', 'what_is_happening', 'new_and_confused', 'hi_mom_im_on_tv', 'wait_whats_going_on', 'lost_in_the_sauce'],
    lines: [
      'wait what is this game',
      'can someone explain the rules',
      'why is he eating the bombs. is that normal',
      'hi I just got here. is the frog winning',
      'who is Chaco and why does he hate the frog',
      'why is there a whole chat. who are all of you.',
      'I joined for the frog and now I am scared',
      'how do you play this',
      'lol wait it is a real game?? I thought it was a bit',
    ],
  },
  spam: {
    weight: 5,
    handles: ['best_followers_4u', 'cheap_views_now', 'FREE_ROBUX_LEGIT', 'promo_bot_4471', 'hot_singles_near_you', 'followerz_2_go'],
    lines: [
      '🔥 BUY 10K FOLLOWERS FOR $3 🔥 CLICK MY PROFILE 🔥',
      'HEY BEAUTIFUL I AM A REAL PERSON PLEASE CLICK MY PROFILE',
      'FREE ROBUX!!! NO SURVEY!!! (SURVEY)',
      'check out my channel!!! I do the SAME THING but WORSE!!!',
      'GET RICH QUICK: turn your frog into 50K/month!!! link in bio!!!',
      'hot singles in your area want to talk about frogs 🐸💋',
      'cheap views, cheap likes, cheap regrets. click here.',
      'subscribe to me and I will subscribe to you and we will both feel nothing',
    ],
  },
  scam: {
    weight: 6,
    handles: ['crypto_kyle_official', 'CEO_of_Bitcoin_real', 'support_agent_maria', 'you_have_won_1', 'invest_with_dave', 'FROGCOIN_moon', 'not_a_scam_trust_me'],
    lines: [
      'Send 1 BTC and I will send you 2 BTC back!! 100% real!!',
      '$FROGE is going to 1000x!! I already bought!! buy after me!!',
      'Dear customer, your frog account has been COMPROMISED. Please send your password to fix.',
      'Congratulations!! You are the 1,000,000th viewer!! You have won a frog!!',
      'DM me for Bitcoin doubling. Not a scam. My mom said so.',
      'This is Microsoft support. Your frog has a virus. Please buy a gift card.',
      'guaranteed 400% returns. the frog told me himself.',
      'I have a once in a lifetime frog investment opportunity. please do not tell your bank.',
      'pls send gift cards to save the frog. the frog is very sick.',
    ],
  },
  romance: {
    weight: 2,
    handles: ['lonely_lisa_82', 'sweet_svetlana_x', 'handsome_you_sexy'],
    lines: [
      'hey handsome, are you watching alone? me too. talk to me 💋',
      'hello dear I am a lonely widow with much money and no frog. please advise.',
      'you look so nice in your username. want to see my photos? (they are of a frog)',
    ],
  },
};

// The prince. He turns up now and then and gets more desperate; the lines are
// played in order. It is the old scam email, taken all the way.
export const PRINCE = {
  handle: 'PrinceOluwaseun_of_Amphibia',
  badge: 'PRINCE',
  lines: [
    'Greetings esteemed friend. I am Prince Oluwaseun, heir to the swamp throne of Amphibia. I require only your bank details and one (1) frog.',
    'DEAREST FRIEND I have 4.5 MILLION dollars trapped in a lily pad and only YOU can free it. Kindly send the frog.',
    'Good day. My previous message was misread. I do NOT want your bank details. I want your bank details AND your password. God bless.',
    'Sir/Madam. The frog on your screen is the lost heir to my late uncle\'s fortune. Please send him to me by post. Regards.',
    'URGENT: I am now prepared to give you 40 percent of my fortune. I have only ONE small fee of 500 dollars in gift cards. This is a good deal.',
    'I have reconsidered. Please just send the frog. I will pay in exposure and swamp.',
    'This is my final message. Please. I am not even a prince. I am a man named Kevin and I am very lost.',
  ],
};

// The moderator, who is losing.
export const MOD = {
  handle: 'MOD_Gary',
  badge: 'MOD',
  lines: [
    'Reminder: no bank details in chat. Thank you.',
    'The frog is NOT for sale. Please stop asking.',
    'Kermit is not a frog developer. Please stop tagging him.',
    'I am one man. I cannot ban all of you fast enough.',
    'If you are here to insult the frog, please do so quietly.',
    'Gary has left the chat. Gary has returned to the chat.',
    'No, the prince is not real. NO. Stop replying to him.',
  ],
  // Shown as system lines, not as a chatter.
  bans: [
    'MOD_Gary timed out best_followers_4u for 600s (spam)',
    'MOD_Gary timed out PrinceOluwaseun_of_Amphibia for 600s (financial solicitation)',
    'MOD_Gary timed out let_him_die for 10s (wishing harm on a frog)',
    'MOD_Gary banned CEO_of_Bitcoin_real (not a CEO)',
    'MOD_Gary timed out xX_Dr_Chaos_Xx for 60s (chaos)',
    'MOD_Gary timed out Kermit_or_nothing for 30s (breach of felt)',
    'MOD_Gary removed 14 messages (they know what they said)',
    'Chat is now in slow mode. Nobody obeys slow mode.',
  ],
};

// Little scenes that play out across a few lines, with whoever is in them.
// [handle, text] in order, a beat apart.
export const FIGHTS = [
  [
    ['Kermit_or_nothing', 'this frog is a cheap knockoff of my boy Kermit'],
    ['froglover_4ever', 'HE IS NOT A KNOCKOFF HE IS HIS OWN FROG'],
    ['Kermit_or_nothing', 'he has no banjo. no soul. no pig.'],
    ['froglover_4ever', 'and Kermit has no bombs. checkmate, felt lover.'],
    ['Kermit_or_nothing', 'you take that back or I swear to Jim Henson'],
    ['MOD_Gary', 'both of you are muted for 30 seconds. go outside.'],
  ],
  [
    ['conspiracy_carol', 'the frog is a government drone and the bombs are surveillance'],
    ['bob_from_accounting', 'Carol it is a video game'],
    ['conspiracy_carol', 'THAT IS WHAT THEY WANT YOU TO SAY BOB'],
    ['bob_from_accounting', 'Carol I love you but you are so wrong'],
    ['conspiracy_carol', 'I am not wrong I am EARLY'],
  ],
  [
    ['originality_police', 'this is a ripoff of Frogger'],
    ['pondmom_87', 'FROGGER IS A RIPOFF OF A ROAD'],
    ['originality_police', 'ok that is actually a good point'],
    ['ripoff_detector', 'no the road was original. frogs were not.'],
    ['pondmom_87', 'everyone in this chat is unwell'],
  ],
  [
    ['let_him_die', 'ok that is enough, kill the frog'],
    ['ribbit_or_riot', 'you touch him and I will find you'],
    ['let_him_die', 'you do not know where I live'],
    ['ribbit_or_riot', 'I do. I have your address. it is on your profile. why is it on your profile.'],
    ['let_him_die', 'oh no'],
    ['MOD_Gary', 'please take this to a private message and never speak of it again'],
  ],
  [
    ['fuck_this_frog', 'this boss is bullshit'],
    ['dumbass_dan', 'the boss is fine you are just bad'],
    ['fuck_this_frog', 'come fight me dan. outside. NOW.'],
    ['dumbass_dan', 'I am in Ohio'],
    ['fuck_this_frog', 'I am in Ohio too. behind the Wendy\'s.'],
    ['dumbass_dan', 'oh. it is on.'],
  ],
  [
    ['CEO_of_Bitcoin_real', 'invest in $FROGE now!!'],
    ['invest_with_dave', 'that is MY scam. get your own.'],
    ['CEO_of_Bitcoin_real', 'this chat is big enough for two scams dave'],
    ['not_a_scam_trust_me', 'I have the best scam and it is 100 percent not a scam'],
    ['MOD_Gary', 'all three of you are banned. this is not a marketplace.'],
  ],
  [
    ['PrinceOluwaseun_of_Amphibia', 'Dear friend. I have a proposal for you.'],
    ['bob_from_accounting', 'is this the one with the 4.5 million'],
    ['PrinceOluwaseun_of_Amphibia', 'The very same. You are clever, sir.'],
    ['bob_from_accounting', 'I already sent it. I am so sorry. I am so sorry Gary.'],
    ['MOD_Gary', 'Bob. BOB.'],
  ],
];

// What the chat says back when something happens in the game.
export const EVENTS = {
  death: [
    'RIP 🐸', 'F', 'oh no. anyway.', 'lmaooooo he is DEAD', 'killed by a HAMBURGER', 'CLIP THAT', 'that is the funniest thing I have seen all week',
    'the frog has been sent to a farm upstate', 'I have never been happier', 'skill issue frog', 'rebirth. rebirth. rebirth.',
    'we are so back (we were never gone)', 'he never stood a chance and I love that for him', 'too soon.', 'I felt that in my SOUL',
    'THE FROG. HE HAS FALLEN. ⚰️', 'run it back',
  ],
  clear: [
    'FROG DID IT', 'holy shit he actually did it', 'LUCKY', 'the bots carried him', 'clap clap clap 👏', 'ok that was clean',
    'did not expect that from a frog', 'W frog', 'my king', 'more bombs eaten than my last three relationships',
    'ratio to the road', 'first try (it was not first try)', 'I cried a little. don\'t tell anyone.',
  ],
  bossStart: {
    default: ['oh here we go', 'he is not going to survive this one', 'BOSS TIME BOSS TIME', 'I did not sign up for this'],
    chaco: ['this is literally Punch-Out', 'Mike Tyson called, he wants his chupacabra back', 'Chaco has a nicer suit than me', 'the frog is getting his ass kicked by a goat sucker', 'is this a Punch-Out ripoff? asking for Nintendo'],
    landlord: ['every landlord I have had. exactly this.', 'tenant rights!! tenant rights!!', 'he wants to raise the rent AND drop a boiler on the frog', 'we do not talk about how he took the deposit'],
    neco: ['the evil twin arc is real', 'mirror frog is hotter no I will not elaborate', 'never trust a reflection'],
    narrator: ['the narrator is lying to you', 'it knows my score. how does it know my score.', 'do not believe a single word'],
    sackman: ['I cannot see anything', 'turn the brightness up please', 'the sack man is my nightmare and my dad'],
    umma: ['UMMA BEAT MY ASS WHEN I WAS SEVEN', 'take off your shoes take off your SHOES', 'nothing in this game is scarier than my mom', 'she is throwing Crocs. it is beautiful.'],
    probe: ['is this Space Invaders? this is Space Invaders', 'the frog has fire breath now. the frog is a dragon.', 'the aliens are hot and I will not be taking questions'],
  },
  bossWin: {
    default: ['FROG WINS', 'boss got folded', 'sit DOWN', 'that is one dead boss'],
    chaco: ['CHACO GOT HIS SUIT DIRTY', 'chupacabra down!! chupacabra DOWN!!', 'goated with the sauce'],
    landlord: ['the landlord has been evicted', 'good. rent is too high.', 'the building was not up to code anyway'],
    neco: ['the mirror is cracked and so is my heart', 'evil twin defeated'],
    narrator: ['the narrator has run out of lies', 'told you he was a liar'],
    sackman: ['someone turn the lights back on', 'the sack man is in the sack now'],
    umma: ['UMMA HAS BEEN DEFEATED. WE ARE ALL ORPHANS.', 'she was proud of him. I saw it. I am crying.', 'never thought I would cheer for the frog over a mom'],
    probe: ['the aliens have gone home', 'we won the invasion by being a frog'],
  },
  bossLose: ['he got folded', 'frog is DOWN', 'that boss is unfair', 'skill issue', 'it is over', 'no no no no no'],
  ad: {
    default: ['not her again', 'who let her in', 'mute her', 'she has a lot to say for a person in a ring light'],
    1: ['okay she is loud', 'girl what is that drink', 'main character energy (derogatory)', 'buy the tea, I dare you'],
    2: ['she is sweating', 'is she okay', 'quota? what quota?', 'I feel bad for her and I do not know why'],
    3: ['she is DRUNK lol', 'that is a lot of wine for a Tuesday', 'she is so cooked', 'someone check on her'],
    4: ['she is not okay. call somebody.', 'the flashlight is real. this is real.', 'buy her ring light. buy it. please.', 'this is the saddest thing I have ever laughed at'],
  },
  achievement: ['achievement? for THAT?', 'participation trophy energy', 'ok you earned that, I guess', 'nobody asked but congrats'],
  stageStart: ['new stage new problems', 'here we go again', 'I am so invested'],
};
